FROM tensorflow/tensorflow:1.15.0-gpu-py3

MAINTAINER Eric Goubault and Sylvie Putot

RUN apt-get -y update
RUN apt install build-essential -y --no-install-recommends
ENV DEBIAN_FRONTEND=noninteractive

RUN apt install -y libgmp3-dev libmpfr-dev libmpfr-doc libmpfr6 gsl-bin libgsl0-dev bison flex gnuplot-x11 libglpk-dev libyaml-cpp-dev m4
RUN apt install -y gcc-8 g++-8
RUN apt install -y libopenmpi-dev
RUN apt install -y python3-pip
#RUN apt install --fix-missing -y emacs
RUN apt install -y git
RUN apt install -y curl wget
RUN apt install -y python3-dev
RUN apt-get -y update
RUN apt install -y python3-matplotlib
RUN apt install -y emacs

RUN pip3 install pip --upgrade
RUN pip install pyyaml

RUN git clone https://github.com/rivapp/CAV21_repeatability_package.git

# verisig 1.0
RUN apt install -y openjdk-8-jdk
RUN cd /CAV21_repeatability_package/verisig/verisig-src && ./gradlew installDist
# verisig 1.0 est /CAV21_repeatability_package/verisig

# verisig 2.0
RUN cd /CAV21_repeatability_package/verisig/flowstar && make
RUN cd /CAV21_repeatability_package/tmp && make
# verisig2.0 is /CAV21_repeatability_package/tmp/flowstar examples cf. https://github.com/rivapp/CAV21_repeatability_package/blob/main/documentation.pdf

# ReachNNStar
RUN cd /CAV21_repeatability_package/ReachNNStar && pip install -r requirements.txt && ./compile.sh
# examples /CAV21_repeatability_package/ReachNNStar/ReachNN/run_ex2_tanh.sh cf. https://github.com/rivapp/CAV21_repeatability_package/blob/main/documentation.pdf

# RINO
RUN cd /home && wget http://www.fadbad.com/download/FADBAD++-2.1.tar.gz && tar -xzvf FADBAD++-2.1.tar.gz && rm FADBAD++-2.1.tar.gz
RUN cd /home && curl -O http://www2.math.uni-wuppertal.de/wrswt/software/filib++/filibsrc-3.0.2.tar.gz && tar -xzvf filibsrc-3.0.2.tar.gz && rm filibsrc-3.0.2.tar.gz

COPY . /home/RINO

RUN cp /home/RINO/FADBAD_Modified/fadbad.h /home/FADBAD++/.
RUN cp /home/RINO/FADBAD_Modified/fadiff.h /home/FADBAD++/.

RUN cd /home/filibsrc && ./configure && make && make install

RUN touch /root/.bashrc.sh
RUN echo "#!/bin/bash" >> /root/.bashrc.sh
RUN echo "export PATH=/usr/local/include:${PATH}" >> /root/.bashrc.sh
RUN echo "export FADBADHOME=/home/FADBAD++" >> /root/.bashrc.sh
RUN echo "export FILIBHOME=/home/filibsrc" >> /root/.bashrc.sh
RUN chmod a+x /root/.bashrc.sh

RUN cd /home/RINO/aaflib-0.1 && make clean && make static

RUN . /root/.bashrc.sh && cd /home/RINO && for f in *.cpp; do iconv -c -f UTF-8 -t US-ASCII $f -o $f; done && for f in *.h; do iconv -c -f UTF-8 -t US-ASCII $f -o $f; done && make clean && make

# Aux files for repeatability

# for Verisig 2.0
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/Verisig2Aux/ACC_tanh_tmp*.model /CAV21_repeatability_package/verisig_models/acc/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/Verisig2Aux/MC_large_sig_tmp*.model /CAV21_repeatability_package/verisig_models/mountain_car_large/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/Verisig2Aux/ex1_sig_tmp*.model /CAV21_repeatability_package/verisig_models/ex1_sig/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/Verisig2Aux/ex1_tanh_tmp*.model /CAV21_repeatability_package/verisig_models/ex1_tanh/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/Verisig2Aux/ex2_sig_tmp*.model /CAV21_repeatability_package/verisig_models/ex2_sig/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/Verisig2Aux/ex2_tanh_tmp*.model /CAV21_repeatability_package/verisig_models/ex2_tanh/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/Verisig2Aux/ex3_sig_tmp*.model /CAV21_repeatability_package/verisig_models/ex3_sig/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/Verisig2Aux/ex3_tanh_tmp*.model /CAV21_repeatability_package/verisig_models/ex3_tanh/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/Verisig2Aux/ex4_sig_tmp*.model /CAV21_repeatability_package/verisig_models/ex4_sig/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/Verisig2Aux/ex4_tanh_tmp*.model /CAV21_repeatability_package/verisig_models/ex4_tanh/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/Verisig2Aux/ex5_sig_tmp*.model /CAV21_repeatability_package/verisig_models/ex5_sig/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/Verisig2Aux/ex5_tanh_tmp*.model /CAV21_repeatability_package/verisig_models/ex5_tanh/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/Verisig2Aux/tora_sig_tmp*.model /CAV21_repeatability_package/verisig_models/tora_sig/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/Verisig2Aux/tora_tanh_tmp*.model /CAV21_repeatability_package/verisig_models/tora_tanh/.

# for RINO
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/RINOConfigFiles/*.txt /home/RINO/Examples/ConfigFiles/.

# for ReachNNStar

# Copy script files
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/script_RINO.sh /home/RINO/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/script_Verisig2.sh /home/RINO/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/script_RINO_001.sh /home/RINO/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/script_Verisig2_005.sh /home/RINO/.
RUN cp /home/RINO/CAVrepeatability2022-auxfiles/script_ReachNNStar.sh /home/RINO/.
RUN chmod a+x /home/RINO/script_RINO.sh
RUN chmod a+x /home/RINO/script_Verisig2.sh
RUN chmod a+x /home/RINO/script_ReachNNStar.sh






